host:
  url: "0.0.0.0"
  port: 8000

data:
  cache: true           # 是否使用缓存的数据
  save: false            # 是否选择缓存数据
  directory: "./data"     # 缓存数据的路径
  lock_timeout: 5       # 文件锁超时时间(秒)

api:
  tb:
    base_url: "https://gateway.1yangai.com/open/"
    auth: "Basic aW50ZXJuYWxVc2VyOkYwODBBRjc1MDQ5NTYxOUQ5RDdFRDhGRDdGRjc4QzAx"
  other:
    base_url: "https://gateway.xiaoduoai.com/open/"
    auth: "Basic F080AF750495619D9D7ED8FD7FF78C01"
  paths:
    logistics: "trade-server/trade/get_logistics_trace_by_order_id"
    order: "trade-server/trade/get_order_by_id"
    product: "goods-center/gc/v2/goods_list"